### ISSUE TITLE
Error: project id required

### ISSUE THREAD

**Issue by michaelcodecany** [anarkrypto/upload-files-to-ipfs-from-browser-panel#3]
https://ipfs.infura.io:5001/api/v0/add?stream-channels=true 401 (Unauthorized)

**Comment by janzheng** [comment]
this is because Infura shut off their public access writable gateway. Anyone know of another public one?

**Comment by kogisin** [comment]
I am getting the same error here. Anyone knows other public node addresses?

**Comment by anarkrypto** [comment]
Hey, I just changed the public node. Now it's working.
